### ISSUE TITLE
Interesting project!

### ISSUE THREAD

**Issue by sangdth** [wsdjeg/notifications.vim#1]
Wonderful idea! I wonder is it possible for display for example comments/mentions from GitHub? I'm using vim with fullscreen and most of the time I disable the Chrome notifications to focus into coding.

I imagine a plugin could help me list only the recent updates based on my current branch/PR/project that I'm on cwd.

**Comment by resolritter** [comment]
@sangdth  Chrome notifications and the like are OS-level notifications. If using Linux, for listening, filtering and scripting on them, it's possible to listen to the events with `dbus-monitor` (assuming your system is using it)

```
dbus-monitor --session interface='org.freedesktop.Notifications' | [your script]
```

Alternatively there are some notification managers which allow you to hide some notifications based on e.g. the title. Some examples:

- https://github.com/dunst-project/dunst
- https://github.com/phuhl/linux_notification_center

This project is for creating notification windows from within the editor, thus by design it has no interaction with OS-level notifications. You should be able to create a Vim/Neovim job listening to e.g. `dbus-monitor` and display the notifications  using this plugin *for the UI*, though. i.e. This plug-in provides the front-end and you have to code the back-end integrations by yourself since that's environment-dependent.

**Comment by sangdth** [comment]
Thank you @resolritter , it's out of my knowledge but definitely I will go back for this :D close for now.
